sudo: required
language: node_js
node_js:
  - v11.10.1

services: 
  - docker

before_install:
  - docker build -t apach/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run apach/react-test npm test -- --coverage

after_success:
  - docker build -t apach/multi-client ./client
  - docker build -t apach/multi-nginx ./nginx
  - docker build -t apach/multi-server ./server
  - docker build -t apach/multi-worker ./worker

  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
  #Take those images and push them to docker hub 
  - docker push apach/multi-client
  - docker push apach/multi-nginx
  - docker push apach/multi-server
  - docker push apach/multi-worker